name: Execute GA Optimization
on:
  repository_dispatch:
    types: [run-ga]
  schedule:
    - cron: '0 0 * * *' # Chạy tự động mỗi ngày

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install paho-mqtt
      - name: Run GA
        env:
          MQTT_USER: ${{ secrets.MQTT_USER }}
          MQTT_PASS: ${{ secrets.MQTT_PASS }}
        run: python ga_optimization.py
